name: step types
on:
  workflow_dispatch

jobs:
 say-hello-bash-inline:
  runs-on: ubuntu-24.04
  steps:
    - run: echo "Hello world"

 say-hello-inline-python:
  runs-on: ubuntu-24.04
  steps:
    - run: print("Hello World!")
      shell: python

 say-hello-action:
  runs-on: ubuntu-24.04
  steps:
    - uses: actions/hello-world-javascript-action@081a6d193d1dcb38460df1e6927486d748730f9d # v1.1
      with:
        who-to-greet: "World"