name: workflows, jobs, and steps
on:
  workflow_dispatch

jobs:
  job-1:
    runs-on: ubuntu-24.04
    steps:
        run: |
          echo " A job consists of one or more steps \n"
          echo " which run sequentially within the \n"
          echo " same compute environment"
  
  job-2:
    runs-on: ubuntu-24.04
    steps:
      run: |
        echo "Multiple jobs can run in parallel"
  
  job-3:
    runs-on: ubuntu-24.04
    needs:
      - job-1
      - job-2
    steps:
      run: |
        echo "They can also depend on one another.."
  
  job-4:
    runs-on: ubuntu-24.04
    needs:
     - job-2
     - job-3
    steps:
      run: |
        echo "..to form a directed acyclic graph (DAG)"
