name: Triggerring-events

on: 
  push:
    branches:
      - "example-branch/**"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "example-branch/filters/*.md" #Include paths
      - "!example-branch/filters/*.txt" #Exclude paths
  
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
    
jobs:
  echo-event:
    runs-on: ubuntu-24.04
    steps:
      - name: Json dump
        run: |
          echo "=== $GITHUB_EVENT_NAME ==="
          cat "$GITHUB_EVENT_PATH"