name: Environment Variables

on:
  workflow_dispatch:
env:
  WORKFLOW_VAR: I_AM_WORKFLOW_SCOPED

jobs:
  job-1:
    runs-on: ubuntu-24.04
    env:
      JOB_VAR: I_AM_JOB_SCOPED
    steps:
      - name: inspect scopes job1 step1
        env:
          STEP_VAR: I_AM_STEP_SCOPED
        run:  |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR" #visible
          echo "JOB_VAR: $JOB_VAR" #visible
          echo "STEP_VAR: $STEP_VAR" #visible

      - name: inspect scoped job1 step2
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR" #visible
          echo "JOB_VAR: $JOB_VAR" #visible
          echo "STEP_VAR: ${STEP_VAR:-<UNSET>}" #not set here
  
  job-2:
    runs-on: ubuntu-24.04
    steps:
      - name: Inspect scopes job2 step1
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR" #visible
          echo "JOB_VAR: ${JOB_VAR:-<UNSET>}" #not set here
          echo "STEP_VAR: ${STEP_VAR:-<UNSET>}" #not set here