#######################################
#### Default Permissions ###############
########################################

permissions:
  contents: read
  packages: read

#######################################
#### All Permissions ###############
########################################

permissions:
  actions: read | write | none
  attestations: read | write | none
  checks: read | write | none
  contents: read | write | none
  deployments: read | write | none
  id-token: read | write | none
  issues: read | write | none
  models: read | write | none
  discussions: read | write | none
  packages: read | write | none
  pages: read | write | none
  pull-requests: read | write | none
  security-events: read | write | none
  statuses: read | write | none