name: permissions
on:
  workflow_dispatch:
    
jobs:
  read-only-pr:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Github CLI
        run: sudo apt-get update -qq && sudo apt-get install -y gh
      - name: List the first 5 open PRs
        run: gh pr list --limit 5
        env:
          GH_TOKEN: ${{ github.token}}
      - name: Attempt to add a label ( expected to fail )
        run: |
          gh pr edit 1 --add-label "documentation"
        env:
          GH_TOKEN: ${{ github.token}}
      - name: Confirm the failure
        if: failure()
        run: echo "Write operation is blocked. Token is read only"
  
  read-write-pr:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Github CLI
        run: sudo apt-get update -qq && sudo apt-get install -y gh
      - name: List the first 5 open PRs
        run: gh pr list --limit 5
        env:
          GH_TOKEN: ${{ github.token}}
      - name: Attempt to add a label ( expected to succeed )
        run: |
          gh pr edit 1 --add-label "documentation"
        env:
          GH_TOKEN: ${{ github.token}}
      - name: Confirm the failure
        if: success()
        run: echo "Write operation succeeded"