name: AWS auth permissions
on:
  workflow_dispatch:
    
jobs:
  # Please do not use this approach ( Less secure )
  auth-to-aws-static:
    runs-on: ubuntu-24.04
    steps:
      - name: "Configure AWS credentials using static key"
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  # Please use the approach ( recommended by GITHUB )
  auth-to-aws-oidc:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: "Configure AWS credentials using oidc"
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam:917774925557:role/github-actions-role